package com.example.greendaotest.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greendaotest.db.bean.ErrorMo;
import com.example.greendaotest.db.bean.UserInfo;

import com.example.greendaotest.db.greendao.ErrorMoDao;
import com.example.greendaotest.db.greendao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig errorMoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final ErrorMoDao errorMoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        errorMoDaoConfig = daoConfigMap.get(ErrorMoDao.class).clone();
        errorMoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        errorMoDao = new ErrorMoDao(errorMoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(ErrorMo.class, errorMoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        errorMoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public ErrorMoDao getErrorMoDao() {
        return errorMoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
